INSERT INTO dice (face1, face2, face3, face4, face5, face6, game_name)
VALUES ('A','A','E','E','G','N','boggle new'),
('E','L','R','T','T','Y','boggle new'),
('A','O','O','T','T','W','boggle new'),
('A','B','B','J','O','O','boggle new'),
('E','H','R','T','V','W','boggle new'),
('C','I','M','O','T','U','boggle new'),
('D','I','S','T','T','Y','boggle new'),
('E','I','O','S','S','T','boggle new'),
('D','E','L','R','V','Y','boggle new'),
('A','C','H','O','P','S','boggle new'),
('H','I','M','N','Qu','U','boggle new'),
('E','E','I','N','S','U','boggle new'),
('E','E','G','H','N','W','boggle new'),
('A','F','F','K','P','S','boggle new'),
('H','L','N','N','R','Z','boggle new'),
('D','E','I','L','R','X','boggle new'),
('A','A','C','I','O','T','boggle old'),
('A','H','M','O','R','S','boggle old'),
('E','G','K','L','U','Y','boggle old'),
('A','B','I','L','T','Y','boggle old'),
('A','C','D','E','M','P','boggle old'),
('E','G','I','N','T','V','boggle old'),
('G','I','L','R','U','W','boggle old'),
('E','L','P','S','T','U','boggle old'),
('D','E','N','O','S','W','boggle old'),
('A','C','E','L','R','S','boggle old'),
('A','B','J','M','O','Qu','boggle old'),
('E','E','F','H','I','Y','boggle old'),
('E','H','I','N','P','S','boggle old'),
('D','K','N','O','T','U','boggle old'),
('A','D','E','N','V','Z','boggle old'),
('B','I','F','O','R','X','boggle old'),
('A','A','A','F','R','S','big boggle original'),
('A','A','E','E','E','E','big boggle original'),
('A','A','F','I','R','S','big boggle original'),
('A','D','E','N','N','N','big boggle original'),
('A','E','E','E','E','M','big boggle original'),
('A','E','E','G','M','U','big boggle original'),
('A','E','G','M','N','N','big boggle original'),
('A','F','I','R','S','Y','big boggle original'),
('B','J','K','Qu','X','Z','big boggle original'),
('C','C','E','N','S','T','big boggle original'),
('C','E','I','I','L','T','big boggle original'),
('C','E','I','P','S','T','big boggle original'),
('D','D','H','N','O','T','big boggle original'),
('D','H','H','L','O','R','big boggle original'),
('D','H','H','L','O','R','big boggle original'),
('D','H','L','N','O','R','big boggle original'),
('E','I','I','I','T','T','big boggle original'),
('C','E','I','L','P','T','big boggle original'),
('E','M','O','T','T','T','big boggle original'),
('E','N','S','S','S','U','big boggle original'),
('F','I','P','R','S','Y','big boggle original'),
('G','O','R','R','V','W','big boggle original'),
('I','P','R','R','R','Y','big boggle original'),
('N','O','O','T','U','W','big boggle original'),
('O','O','O','T','T','U','big boggle original'),
('A','A','A','F','R','S','big boggle deluxe'),
('A','A','E','E','E','E','big boggle deluxe'),
('A','A','F','I','R','S','big boggle deluxe'),
('A','D','E','N','N','N','big boggle deluxe'),
('A','E','E','E','E','M','big boggle deluxe'),
('A','E','E','G','M','U','big boggle deluxe'),
('A','E','G','M','N','N','big boggle deluxe'),
('A','F','I','R','S','Y','big boggle deluxe'),
('B','J','K','Qu','X','Z','big boggle deluxe'),
('C','C','N','S','T','W','big boggle deluxe'),
('C','E','I','I','L','T','big boggle deluxe'),
('C','E','I','P','S','T','big boggle deluxe'),
('D','D','L','N','O','R','big boggle deluxe'),
('D','H','H','L','O','R','big boggle deluxe'),
('D','H','H','N','O','T','big boggle deluxe'),
('D','H','L','N','O','R','big boggle deluxe'),
('E','I','I','I','T','T','big boggle deluxe'),
('C','E','I','L','P','T','big boggle deluxe'),
('E','M','O','T','T','T','big boggle deluxe'),
('E','N','S','S','S','U','big boggle deluxe'),
('F','I','P','R','S','Y','big boggle deluxe'),
('G','O','R','R','V','W','big boggle deluxe'),
('H','I','P','R','R','Y','big boggle deluxe'),
('N','O','O','T','U','W','big boggle deluxe'),
('O','O','O','T','T','U','big boggle deluxe'),
('A','A','A','F','R','S','big boggle 2012'),
('A','A','E','E','E','E','big boggle 2012'),
('A','A','F','I','R','S','big boggle 2012'),
('A','D','E','N','N','N','big boggle 2012'),
('A','E','E','E','E','M','big boggle 2012'),
('A','E','E','G','M','U','big boggle 2012'),
('A','E','G','M','N','N','big boggle 2012'),
('A','F','I','R','S','Y','big boggle 2012'),
('B','B','J','K','X','Z','big boggle 2012'),
('C','C','E','N','S','T','big boggle 2012'),
('E','I','I','L','S','T','big boggle 2012'),
('C','E','I','P','S','T','big boggle 2012'),
('D','D','H','N','O','T','big boggle 2012'),
('D','H','H','L','O','R','big boggle 2012'),
('D','H','H','N','O','W','big boggle 2012'),
('D','H','L','N','O','R','big boggle 2012'),
('E','I','I','I','T','T','big boggle 2012'),
('E','I','L','P','S','T','big boggle 2012'),
('E','M','O','T','T','T','big boggle 2012'),
('E','N','S','S','S','U','big boggle 2012'),
('Qu','In','Th','Er','He','An','big boggle 2012'),
('G','O','R','R','V','W','big boggle 2012'),
('I','P','R','S','Y','Y','big boggle 2012'),
('N','O','O','T','U','W','big boggle 2012'),
('O','O','O','T','T','U','big boggle 2012');
INSERT INTO dice (face1, face2, face3, face4, face5, face6, face7, face8, face9, face10, face11, face12, face13, face14, face15, face16, face17, face18, face19, face20, game_name)
('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','R','S','T','W','scattergories');
