INSERT INTO cattegories (cattegory, game_name, second_game, third_game, fourth_game, list_group)
VALUES ("A BOY'S NAME",'scattergories','1'),
("U.S. CITIES",'scattergories','1'),
("THINGS THAT ARE COLD",'scattergories','1'),
("SCHOOL SUPPLIES",'scattergories','1'),
("PRO SPORTS TEAMS",'scattergories','1'),
("INSECTS",'scattergories','1'),
("BREAKFAST FOODS",'scattergories','1'),
("FURNITURE",'scattergories','1'),
("TV SHOWS",'scattergories','1'),
("THINGS FOUND IN THE OCEAN",'scattergories','1'),
("PRESIDENTS",'scattergories','1'),
("PRODUCT NAMES",'scattergories','1'),
("VEGETABLES",'scattergories','2'),
("STATES",'scattergories','2'),
("THINGS YOU THROW AWAY",'scattergories','2'),
("OCCUPATIONS",'scattergories','2'),
("APPLIANCES",'scattergories','2'),
("CARTOON CHARACTERS",'scattergories','2'),
("TYPES OF DRINK",'scattergories','2'),
("MUSICAL GROUPS",'scattergories','2'),
("STORE NAMES",'scattergories','2'),
("THINGS AT A FOOTBALL GAME",'scattergories','2'),
("TREES",'scattergories','2'),
("PERSONALITY TRAITS",'scattergories','2'),
("ARTICLES OF CLOTHING",'scattergories','3'),
("DESSERTS",'scattergories','3'),
("CAR PARTS",'scattergories','3'),
("THINGS FOUND ON A MAP",'scattergories','3'),
("ATHLETES",'scattergories','3'),
("4-LETTER WORDS",'scattergories','3'),
("ITEMS IN A REFRIGERATOR",'scattergories','3'),
("FARM ANIMALS",'scattergories','3'),
("STREET NAMES",'scattergories','3'),
("THINGS AT THE BEACH",'scattergories','3'),
("COLORS",'scattergories','3'),
("TOOLS",'scattergories','3'),
("SPORTS",'scattergories','4'),
("SONG TITLES",'scattergories','4'),
("PARTS OF THE BODY",'scattergories','4'),
("ETHNIC FOODS",'scattergories','4'),
("THINGS YOU SHOUT",'scattergories','4'),
("BIRDS",'scattergories','4'),
("A GIRL'S NAME",'scattergories','4'),
("WAYS TO GET FROM HERE TO THERE",'scattergories','4'),
("ITEMS IN A KITCHEN",'scattergories','4'),
("VILLAINS / MONSTERS",'scattergories','4'),
("FLOWERS",'scattergories','4'),
("THINGS YOU REPLACE",'scattergories','4'),
("SANDWICHES",'scattergories','5'),
("ITEMS IN A CATALOG",'scattergories','5'),
("WORLD LEADERS / POLITICIANS",'scattergories','5'),
("SCHOOL SUBJECTS",'scattergories','5'),
("EXCUSES FOR BEING LATE",'scattergories','5'),
("ICE CREAM FLAVORS",'scattergories','5'),
("THINGS THAT JUMP / BOUNCE",'scattergories','5'),
("TELEVISION STARS",'scattergories','5'),
("THINGS IN A PARK",'scattergories','5'),
("FOREIGN CITIES",'scattergories','5'),
("STONES / GEMS",'scattergories','5'),
("MUSICAL INSTRUMENTS",'scattergories','5'),
("THINGS THAT ARE STICKY",'scattergories','6'),
("AWARDS / CEREMONIES",'scattergories','6'),
("CARS",'scattergories','6'),
("SPICES / HERBS",'scattergories','6'),
("BAD HABITS",'scattergories','6'),
("COSMETICS / TOILETRIES",'scattergories','6'),
("CELEBRITIES",'scattergories','6'),
("COOKING UTENSILS",'scattergories','6'),
("REPTILES / AMPHIBIANS",'scattergories','6'),
("PARKS",'scattergories','6'),
("LEISURE ACTIVITIES",'scattergories','6'),
("THINGS YOU'RE ALLERGIC TO",'scattergories','6'),
("FICTIONAL CHARACTERS",'scattergories','7'),
("MENU ITEMS",'scattergories','7'),
("MAGAZINES",'scattergories','7'),
("CAPITALS",'scattergories','7'),
("KINDS OF CANDY",'scattergories','7'),
("ITEMS YOU SAVE UP TO BUY",'scattergories','7'),
("FOOTWEAR",'scattergories','7'),
("SOMETHING YOU KEEP HIDDEN",'scattergories','7'),
("ITEMS IN A SUITCASE",'scattergories','7'),
("THINGS WITH TAILS",'scattergories','7'),
("SPORTS EQUIPMENT",'scattergories','7'),
("CRIMES",'scattergories','7'),
("NICKNAMES",'scattergories','8'),
("THINGS IN THE SKY",'scattergories','8'),
("PIZZA TOPPINGS",'scattergories','8'),
("COLLEGES / UNIVERSITIES",'scattergories','8'),
("FISH",'scattergories','8'),
("COUNTRIES",'scattergories','8'),
("THINGS THAT HAVE SPOTS",'scattergories','8'),
("HISTORICAL FIGURES",'scattergories','8'),
("SOMETHING YOU'RE AFRAID OF",'scattergories','8'),
("TERMS OF MEASUREMENT",'scattergories','8'),
("ITEMS IN THIS ROOM",'scattergories','8'),
("BOOK TITLES",'scattergories','8'),
("RESTAURANTS",'scattergories','9'),
("NOTORIOUS PEOPLE",'scattergories','9'),
("FRUITS",'scattergories','9'),
("THINGS IN A MEDICINE CABINET",'scattergories','9'),
("TOYS",'scattergories','9'),
("HOUSEHOLD CHORES",'scattergories','9'),
("BODIES OF WATER",'scattergories','9'),
("AUTHORS",'scattergories','9'),
("HALLOWEEN COSTUMES",'scattergories','9'),
("WEAPONS",'scattergories','9'),
("THINGS THAT ARE ROUND",'scattergories','9'),
("WORDS ASSOCIATED WITH EXERCISE",'scattergories','9'),
("HEROES",'scattergories','10'),
("GIFTS / PRESENTS",'scattergories','10'),
("TERMS OF ENDEARMENT",'scattergories','10'),
("KINDS OF DANCES",'scattergories','10'),
("THINGS THAT ARE BLACK",'scattergories','10'),
("VEHICLES",'scattergories','10'),
("TROPICAL LOCATIONS",'scattergories','10'),
("COLLEGE MAJORS",'scattergories','10'),
("DAIRY PRODUCTS",'scattergories','10'),
("THINGS IN A SOUVENIR SHOP",'scattergories','10'),
("ITEMS IN YOUR PURSE / WALLET",'scattergories','10'),
("WORLD RECORDS",'scattergories','10'),
("BABY FOODS",'scattergories','11'),
("FAMOUS DUOS AND TRIOS",'scattergories','11'),
("THINGS FOUND IN A DESK",'scattergories','11'),
("VACATION SPOTS",'scattergories','11'),
("DISEASES",'scattergories','11'),
("WORDS ASSOCIATED WITH MONEY",'scattergories','11'),
("ITEMS IN A VENDING MACHINE",'scattergories','11'),
("MOVIE TITLES",'scattergories','11'),
("GAMES",'scattergories','11'),
("THINGS THAT YOU WEAR",'scattergories','11'),
("BEERS",'scattergories','11'),
("THINGS AT A CIRCUS",'scattergories','11'),
("FAMOUS FEMALES",'scattergories','12'),
("MEDICINE / DRUGS",'scattergories','12'),
("THINGS MADE OF METAL",'scattergories','12'),
("HOBBIES",'scattergories','12'),
("PEOPLE IN UNIFORM",'scattergories','12'),
("THINGS YOU PLUG IN",'scattergories','12'),
("ANIMALS",'scattergories','12'),
("LANGUAGES",'scattergories','12'),
("NAMES USED IN THE BIBLE",'scattergories','12'),
("JUNK FOOD",'scattergories','12'),
("THINGS THAT GROW",'scattergories','12'),
("COMPANIES",'scattergories','12'),
("FROM TV, MOVIES AND BOOKS",'scattergories','R1'),
("DANGEROUS ANIMALS",'scattergories','R1'),
("ANIMALS THAT SWIM",'scattergories','R1'),
("FOUR-LEGGED CREATURES",'scattergories','R1'),
("THINGS ANIMALS EAT",'scattergories','R1'),
("PETS",'scattergories','R1'),
("ANIMALS FOUND IN FOREIGN LANDS",'scattergories','R1'),
("ANIMAL NOISES",'scattergories','R1'),
("AT THE ZOO",'scattergories','R1'),
("MASCOTS",'scattergories','R1'),
("ANIMALS THAT ADVERTISE PRODUCTS",'scattergories','R1'),
("ANIMALS THAT FLY",'scattergories','R1'),
("MOVIE STARS (LIVING)",'scattergories','R2'),
("MOVIE STARS (DEAD)",'scattergories','R2'),
("POLITICAL FIGURES",'scattergories','R2'),
("SPORTS PERSONALITIES",'scattergories','R2'),
("SEX SYMBOLS",'scattergories','R2'),
("NEWSCASTERS / JOURNALISTS",'scattergories','R2'),
("SINGERS",'scattergories','R2'),
("ARTISTS",'scattergories','R2'),
("CELEBRITIES YOU'D LIKE TO MEET",'scattergories','R2'),
("CHILDREN",'scattergories','R2'),
("STARS WHO APPEAR IN BOTH TV AND MOVIES",'scattergories','R2'),
("MILITARY LEADERS",'scattergories','R2'),
("THINGS THAT SMELL BAD",'scattergories','R3'),
("THINGS YOU CAN'T SEE",'scattergories','R3'),
("THINGS YOU DON'T WANT TO HEAR",'scattergories','R3'),
("THINGS THAT FEEL SOFT",'scattergories','R3'),
("THINGS THAT TASTE SPICY",'scattergories','R3'),
("THINGS THAT SMELL GOOD",'scattergories','R3'),
("THINGS THAT ARE RED",'scattergories','R3'),
("THINGS YOU NEVER TASTED",'scattergories','R3'),
("THINGS THAT ARE LOUD",'scattergories','R3'),
("THINGS YOU SHOULDN'T TOUCH",'scattergories','R3'),
("THINGS YOU SEE IN A CITY",'scattergories','R3'),
("THINGS THAT FEEL HOT",'scattergories','R3'),
("PRODUCE",'scattergories','R4'),
("COCKTAILS",'scattergories','R4'),
("SEAFOOD",'scattergories','R4'),
("LOW CALORIE FOODS",'scattergories','R4'),
("FOOD FOUND IN A DELI",'scattergories','R4'),
("BREAKFAST CEREALS",'scattergories','R4'),
("ANY GREEN FOOD OR DRINK",'scattergories','R4'),
("SOFT DRINKS",'scattergories','R4'),
("DISGUSTING THINGS TO EAT OR DRINK",'scattergories','R4'),
("HORS D'OEUVRES",'scattergories','R4'),
("FRIED FOODS",'scattergories','R4'),
("ON A WINE LIST",'scattergories','R4'),
("ITALIAN FOOD",'scattergories','R5'),
("FAST FOOD",'scattergories','R5'),
("KINDS OF SOUP",'scattergories','R5'),
("SNACKS",'scattergories','R5'),
("FOOD YOU EAT RAW",'scattergories','R5'),
("FOOD FOUND IN A CASSEROLE",'scattergories','R5'),
("FOOD AT A CARNIVAL OR FAIR",'scattergories','R5'),
("HEALTH FOOD",'scattergories','R5'),
("CANNED FOOD",'scattergories','R5'),
("CHINESE FOOD",'scattergories','R5'),
("FOUND IN A SALAD BAR",'scattergories','R5'),
("MEXICAN FOOD",'scattergories','R5'),
("PEOPLE YOU ADMIRE",'scattergories','R6'),
("LAST NAMES",'scattergories','R6'),
("PEOPLE WHO DO DANGEROUS JOBS",'scattergories','R6'),
("COUPLES",'scattergories','R6'),
("PEOPLE WHO GO DOOR-TO-DOOR",'scattergories','R6'),
("NATIONALITIES",'scattergories','R6'),
("PEOPLE WHO WORK AT NIGHT",'scattergories','R6'),
("PEOPLE'S NAMES USED IN SONGS",'scattergories','R6'),
("PEOPLE YOU AVOID",'scattergories','R6'),
("SOMEONE FROM YOUR PAST",'scattergories','R6'),
("TITLES PEOPLE HAVE",'scattergories','R6'),
("PEOPLE WHO WORK ALONE",'scattergories','R6'),
("IN EUROPE",'scattergories','R7'),
("HONEYMOON SPOTS",'scattergories','R7'),
("COLD CLIMATES",'scattergories','R7'),
("PLACES YOU WOULDN'T WANT TO LIVE",'scattergories','R7'),
("ISLANDS",'scattergories','R7'),
("IN NORTH AMERICA",'scattergories','R7'),
("IN YOUR HOMETOWN",'scattergories','R7'),
("WITH A HIGH ALTITUDE",'scattergories','R7'),
("NOT ON THE PLANET EARTH",'scattergories','R7'),
("IN NATIONAL GEOGRAPHIC MAGAZINE",'scattergories','R7'),
("FICTITIOUS PLACES",'scattergories','R7'),
("WARM CLIMATES",'scattergories','R7'),
("THINGS FOUND IN THE WATER",'scattergories','R8'),
("GIFTS FOR THE BRIDE AND GROOM",'scattergories','R8'),
("TOURIST ATTRACTIONS",'scattergories','R8'),
("REASONS TO CALL EMERGENCY 911",'scattergories','R8'),
("THINGS YOU CARRY",'scattergories','R8'),
("THINGS FROM A STATIONERY STORE",'scattergories','R8'),
("REASONS TO QUIT YOUR JOB",'scattergories','R8'),
("THINGS WORN FROM THE WAIST UP",'scattergories','R8'),
("THINGS THAT ARE WHITE",'scattergories','R8'),
("THINGS FOUND IN A BASEMENT / CELLAR",'scattergories','R8'),
("THINGS WITH STRIPES",'scattergories','R8'),
("THINGS YOU NEED TICKETS TO SEE",'scattergories','R8'),
("MATH TERMS",'scattergories','R9'),
("THINGS YOU DO IN STUDY HALL",'scattergories','R9'),
("THINGS FOUND IN A LOCKER",'scattergories','R9'),
("THINGS YOU STUDY IN HISTORY",'scattergories','R9'),
("SCIENCE TERMS",'scattergories','R9'),
("AFTER SCHOOL ACTIVITIES",'scattergories','R9'),
("REASONS TO GO TO THE PRINCIPAL'S OFFICE",'scattergories','R9'),
("REASONS TO BE ABSENT",'scattergories','R9'),
("THINGS IN A CLASSROOM",'scattergories','R9'),
("THINGS YOU STUDY IN GEOGRAPHY",'scattergories','R9'),
("THINGS YOU DO IN GYM CLASS",'scattergories','R9'),
("FOUND IN THE CAFETERIA",'scattergories','R9'),
("TEAM NAMES",'scattergories','R10'),
("PLAYED INSIDE",'scattergories','R10'),
("PLAYED OUTSIDE",'scattergories','R10'),
("BOOKS, MOVIES, OR TV SHOWS ABOUT SPORTS",'scattergories','R10'),
("SPORTS TERMS",'scattergories','R10'),
("FEMALE ATHLETES",'scattergories','R10'),
("SPORTING EVENTS",'scattergories','R10'),
("A FOOTBALL PLAYER'S NAME",'scattergories','R10'),
("A BASEBALL PLAYER'S NAME",'scattergories','R10'),
("THINGS YOU SCREAM AT OFFICIALS",'scattergories','R10'),
("OLYMPIC EVENTS",'scattergories','R10'),
("ATHLETES WHO DO COMMERCIALS",'scattergories','R10'),
("CANCELLED TV SHOWS",'scattergories','R11'),
("MOVIES ON TV",'scattergories','R11'),
("CHILDREN'S TV SHOWS",'scattergories','R11'),
("COMEDY SHOWS",'scattergories','R11'),
("LONG-RUNNING TV SERIES",'scattergories','R11'),
("SHOWS YOU DON'T LIKE",'scattergories','R11'),
("THINGS SOLD IN COMMERCIALS",'scattergories','R11'),
("TV CHARACTER NAMES",'scattergories','R11'),
("FEMALE STARS",'scattergories','R11'),
("MALE STARS",'scattergories','R11'),
("THINGS YOU DO WHILE WATCHING TV",'scattergories','R11'),
("DAYTIME TV SHOWS",'scattergories','R11'),
("WORDS ENDING IN "LY"",'scattergories','R12'),
("NOUNS",'scattergories','R12'),
("ACTION WORDS",'scattergories','R12'),
("ABBREVIATIONS",'scattergories','R12'),
("FOREIGN WORDS",'scattergories','R12'),
("5-LETTER WORDS",'scattergories','R12'),
("WORDS THAT END IN "ING"",'scattergories','R12'),
("WORDS WITH A DOUBLE LETTER",'scattergories','R12'),
("WORDS SAID IN ANGER",'scattergories','R12'),
("ADJECTIVES",'scattergories','R12'),
("WORDS ENDING IN "ED"",'scattergories','R12'),
("3-LETTER WORDS",'scattergories','R12'),
("THINGS AT A PICNIC",'scattergories','13'),
("THINGS THAT ARE SOFT",'scattergories','13'),
("THINGS IN A SCIENCE FICTION MOVIE",'scattergories','13'),
("THINGS AT THE WHITE HOUSE",'scattergories','13'),
("THINGS THAT KIDS PLAY WITH",'scattergories','13'),
("THINGS AT A WEDDING",'scattergories','13'),
("HOT PLACES",'scattergories','13'),
("THINGS IN OUTER SPACE",'scattergories','13'),
("FOUND IN A COLLEGE DORM",'scattergories','13'),
("THINGS AT A DINER",'scattergories','13'),
("FAMOUS SINGERS",'scattergories','13'),
("THINGS AT AN AMUSEMENT PARK",'scattergories','13'),
("WORN ABOVE THE WAIST",'scattergories','14'),
("THINGS THAT ARE BRIGHT",'scattergories','14'),
("THINGS THAT HAVE NUMBERS",'scattergories','14'),
("FOUND IN A GYM / HEALTH CLUB",'scattergories','14'),
("THINGS ON A SAFARI",'scattergories','14'),
("WAYS TO SAY HI AND BYE",'scattergories','14'),
("THINGS FROM THE SIXTIES",'scattergories','14'),
("HOLIDAY THINGS",'scattergories','14'),
("ITEMS IN AN OFFICE",'scattergories','14'),
("THINGS IN PAIRS OR SETS",'scattergories','14'),
("THINGS ON A HIGHWAY",'scattergories','14'),
("THINGS IN LAS VEGAS",'scattergories','14'),
("THINGS AT A ZOO",'scattergories','15'),
("THINGS WITH MOTORS",'scattergories','15'),
("THINGS THAT FLY",'scattergories','15'),
("FOUND AT A SALAD BAR",'scattergories','15'),
("WORDS ENDING IN "LY"",'scattergories','15'),
("THINGS ON A HIKING TRIP",'scattergories','15'),
("THINGS IN A HOTEL",'scattergories','15'),
("HEALTHY FOODS",'scattergories','15'),
("FOUND IN A CLASSROOM",'scattergories','15'),
("PARTY THINGS",'scattergories','15'),
("REASONS TO SKIP SCHOOL / WORK",'scattergories','15'),
("TITLES PEOPLE HAVE",'scattergories','15'),
("THINGS IN A DESERT",'scattergories','16'),
("THINGS IN A MYSTERY NOVEL",'scattergories','16'),
("COMPUTER LINGO",'scattergories','16'),
("LOUDS THINGS",'scattergories','16'),
("KINDS OF SOUPS / STEWS",'scattergories','16'),
("MATH TERMS",'scattergories','16'),
("UNDERGROUND THINGS",'scattergories','16'),
("THINGS IN THE WILD WEST",'scattergories','16'),
("THINGS IN AN AIRPORT",'scattergories','16'),
("WORDS WITH DOUBLE LETTERS",'scattergories','16'),
("FOUND IN NEW YORK CITY",'scattergories','16'),
("THINGS IN FAIRY TALES",'scattergories','16'),
("THINGS IN A CHURCH",'scattergories','B1'),
("ANIMALS ON THE ARK",'scattergories','B1'),
("WOMEN IN THE BIBLE",'scattergories','B1'),
("CITIES IN ISRAEL",'scattergories','B1'),
("THINGS TO EAT",'scattergories','B1'),
("SINS",'scattergories','B1'),
("COLORS IN THE BIBLE",'scattergories','B1'),
("TRADES / JOBS",'scattergories','B1'),
("NAMES FOR CHRIST",'scattergories','B1'),
("MUSICAL INSTRUMENTS",'scattergories','B1'),
("THINGS THAT ARE RED",'scattergories','B1'),
("PLACES CHRIST WALKED",'scattergories','B1'),
("OCCASIONS FOR ANOINTING WITH OIL",'scattergories','B2'),
("CITIES IN JUDAH",'scattergories','B2'),
("BOOKS IN THE NEW TESTAMENT",'scattergories','B2'),
("PROPHETS",'scattergories','B2'),
("NUMBERS",'scattergories','B2'),
("WOMEN WHO DISOBEYED GOD",'scattergories','B2'),
("MIRACLES PERFORMED BY JESUS",'scattergories','B2'),
("WEAPONS",'scattergories','B2'),
("GEMS / PRECIOUS STONES",'scattergories','B2'),
("BLESSINGS",'scattergories','B2'),
("THINGS FOUND AROUND GOD'S THRONE",'scattergories','B2'),
("RIVERS",'scattergories','B2'),
("PROMISES OF GOD",'scattergories','B3'),
("THINGS THAT DEFILE",'scattergories','B3'),
("ANIMALS IN THE NEW TESTAMENT",'scattergories','B3'),
("PLACES GOD APPEARED TO MAN",'scattergories','B3'),
("CITIES UNDER ROMAN CONTROL",'scattergories','B3'),
("THINGS USED TO BUILD THE TEMPLE",'scattergories','B3'),
("WARRIORS",'scattergories','B3'),
("THINGS THAT ARE COUNTED",'scattergories','B3'),
("PLAGUES",'scattergories','B3'),
("FRUITS OF THE SPIRIT",'scattergories','B3'),
("COMMANDMENTS",'scattergories','B3'),
("QUEENS",'scattergories','B3'),
("REASONS FOR SACRIFICE",'scattergories','B4'),
("FATHERS",'scattergories','B4'),
("THINGS ASSOCIATED WITH CREATION",'scattergories','B4'),
("ANIMALS THAT WERE WORSHIPPED",'scattergories','B4'),
("TOOLS",'scattergories','B4'),
("CITIES UNDER ASSYRIAN CONTROL",'scattergories','B4'),
("CURSES",'scattergories','B4'),
("THINGS THAT SEPARATE US FROM GOD",'scattergories','B4'),
("JUDGES",'scattergories','B4'),
("THINGS THAT BRING BLESSING",'scattergories','B4'),
("PARABLES OF JESUS",'scattergories','B4'),
("ANGELS",'scattergories','B4'),
("PROPHESIES ABOUT CHRIST",'scattergories','B5'),
("PLACES PEOPLE HID",'scattergories','B5'),
("THINGS YOU SEE IN A CITY",'scattergories','B5'),
("KINGS",'scattergories','B5'),
("MIRACLES PERFORMED BY THE HOLY SPIRIT",'scattergories','B5'),
("PROMISES MADE BY MEN",'scattergories','B5'),
("TRIBES OF ISRAEL",'scattergories','B5'),
("PEOPLE IN THE GENEOLOGY OF CHRIST",'scattergories','B5'),
("THNGS THAT SEPARATE US FROM EACH OTHER",'scattergories','B5'),
("THINGS ASSOCIATED WITH CHRISTMAS",'scattergories','B5'),
("THINGS ASSOCIATED WITH ABRAHAM",'scattergories','B5'),
("THINGS TO FORGIVE",'scattergories','B5'),
("PRIESTS",'scattergories','B6'),
("ANIMALS THAT ARE EXTINCT",'scattergories','B6'),
("PLACES FROM WHERE PEOPLE FLED",'scattergories','B6'),
("MOTHERS",'scattergories','B6'),
("MANIFESTATIONS OF GOD",'scattergories','B6'),
("NAMES FOR SATAN",'scattergories','B6'),
("PLANTS",'scattergories','B6'),
("PROPHESIES IN THE OLD TESTAMENT",'scattergories','B6'),
("THINGS THAT BRING A CURSE",'scattergories','B6'),
("PEOPLE WHO MADE EXCUSES",'scattergories','B6'),
("TERMS OF MEASUREMENT",'scattergories','B6'),
("NATIONS / PEOPLE GROUPS",'scattergories','B6'),
("THINGS THAT HURT",'scattergories','B7'),
("MEN IN THE BIBLE",'scattergories','B7'),
("ANIMALS NAMED IN VISIONS",'scattergories','B7'),
("ARMOR OF GOD",'scattergories','B7'),
("WIVES",'scattergories','B7'),
("THINGS ASSOCIATED WITH DAVID",'scattergories','B7'),
("PLACES TO WHERE PEOPLE FLED",'scattergories','B7'),
("MINISTRIES",'scattergories','B7'),
("THINGS THAT ARE COUNTED",'scattergories','B7'),
("ISLANDS",'scattergories','B7'),
("THINGS ASSOCIATED WITH HEAVEN",'scattergories','B7'),
("PEOPLE WHO WEPT",'scattergories','B7'),
("PROPHESIES IN THE NEW TESTAMENT",'scattergories','B8'),
("THINGS ASSOCIATED WITH JOSEPH",'scattergories','B8'),
("DISCIPLES OF CHRIST",'scattergories','B8'),
("THINGS USED TO HEAL",'scattergories','B8'),
("METALS",'scattergories','B8'),
("PLACES BATTLES WERE FOUGHT",'scattergories','B8'),
("FIRST BORN SONS",'scattergories','B8'),
("THINGS ASSOCIATED WITH PAUL",'scattergories','B8'),
("PROMISES MADE BY WOMEN",'scattergories','B8'),
("THINGS ASSOCIATED WITH SOLOMON",'scattergories','B8'),
("WOMEN IN THE OLD TESTAMENT",'scattergories','B8'),
("THINGS ASSOCIATED WITH THE DISCIPLES",'scattergories','B8'),
("PLACES PEOPLE WERE HEALED",'scattergories','B9'),
("ENEMIES OF THE HEBREWS",'scattergories','B9'),
("BOOKS OF THE OLD TESTAMENT",'scattergories','B9'),
("HUSBANDS",'scattergories','B9'),
("FALSE GODS",'scattergories','B9'),
("THINGS TO WEAR",'scattergories','B9'),
("INSECTS",'scattergories','B9'),
("THINGS FOUND IN THE PALACE",'scattergories','B9'),
("GIFTS",'scattergories','B9'),
("CITIES IN THE NEW TESTAMENT",'scattergories','B9'),
("THINGS ASSOCIATED WITH THE HOLY SPIRIT",'scattergories','B9'),
("THINGS ASSOCIATED WITH ISAIAH",'scattergories','B9'),
("MOUNTAINS",'scattergories','B10'),
("NAMES FOR THE HOLY SPIRIT",'scattergories','B10'),
("ANIMALS USED IN SACRIFICE",'scattergories','B10'),
("PLACES ALTERS WERE BUILT",'scattergories','B10'),
("COUPLES",'scattergories','B10'),
("CHURCHES",'scattergories','B10'),
("THINGS ASSOCIATED WITH MOSES",'scattergories','B10'),
("EVIL KINGS",'scattergories','B10'),
("PEOPLE WHO WERE HEALED",'scattergories','B10'),
("WOMEN IN THE NEW TESTAMENT",'scattergories','B10'),
("THINGS ASSOCIATED WITH JESUS",'scattergories','B10'),
("THINGS THAT ARE A MYSTERY",'scattergories','B10'),
("NAMES FOR GOD THE FATHER",'scattergories','B11'),
("EXAMPLES OF WISDOM",'scattergories','B11'),
("MEN WHO DISOBEYED GOD",'scattergories','B11'),
("LAWS GIVEN TO ISRAEL",'scattergories','B11'),
("MIRACLES FROM GOD",'scattergories','B11'),
("ANIMALS THAT HURT PEOPLE",'scattergories','B11'),
("THINGS ASSOCIATED WITH ABRAHAM",'scattergories','B11'),
("GOOD KINGS",'scattergories','B11'),
("PLACES MISSIONARIES VISITED",'scattergories','B11'),
("THINGS ASSOCIATED WITH PROPHECY",'scattergories','B11'),
("MEN IN THE NEW TESTAMENT",'scattergories','B11'),
("EXAMPLES OF GOD'S GRACE",'scattergories','B11'),
("PROPHECIES FULFILLED IN THE NEW TESTAMENT",'scattergories','B12'),
("PEOPLE WHO REPENTED",'scattergories','B12'),
("EXAMPLES OF FOOLISHNESS",'scattergories','B12'),
("ANIMALS USED BY GOD'S PEOPLE",'scattergories','B12'),
("CITIES IN THE OLD TESTAMENT",'scattergories','B12'),
("THINGS ASSOCIATED WITH EGYPT",'scattergories','B12'),
("ENEMIES OF THE CHURCH",'scattergories','B12'),
("THINGS FOUND IN THE TEMPLE",'scattergories','B12'),
("THINGS ASSOCIATED WITH SAMSON",'scattergories','B12'),
("PLACES PEOPLE WERE HELD PRISONER",'scattergories','B12'),
("THINGS ASSOCIATED WITH PETER",'scattergories','B12'),
("MEN IN THE OLD TESTAMENT",'scattergories','B12'),
("CHRISTMAS THINGS",'scattergories','J1'),
("SUMMER VACATION THINGS",'scattergories','J1'),
("WINTER VACATION THINGS",'scattergories','J1'),
("HALLOWEEN THINGS",'scattergories','J1'),
("HOLIDAY FOOD OR DRINK",'scattergories','J1'),
("VALENTINE'S DAY THINGS",'scattergories','J1'),
("THINGS IN A FOOD FIGHT",'scattergories','J2'),
("THINGS YOU EAT OR DRINK AT LUNCH",'scattergories','J2'),
("THINGS ON A HAMBURGER",'scattergories','J2'),
("YUCKY THINGS TO EAT OR DRINK",'scattergories','J2'),
("YUMMY THINGS MOM DOESN'T WANT YOU TO EAT",'scattergories','J2'),
("THINGS YOU EAT WITH YOUR FINGERS",'scattergories','J2'),
("WILD ANIMALS",'scattergories','J3'),
("THINGS YOU FEED YOUR PET",'scattergories','J3'),
("NAMES FOR A DOG OR CAT",'scattergories','J3'),
("ANIMALS THAT MAKE BAD PETS",'scattergories','J3'),
("ANIMALS THAT FLY OR SWIM",'scattergories','J3'),
("STUFFED ANIMALS",'scattergories','J3'),
("THINGS YOU DO AT RECESS",'scattergories','J4'),
("REASONS YOU DIDN'T DO YOUR HOMEWORK",'scattergories','J4'),
("A CLASSMATE'S NAME",'scattergories','J4'),
("EXCUSES TO LEAVE THE CLASSROOM",'scattergories','J4'),
("SOMETHING YOU STUDY",'scattergories','J4'),
("PLACES TO GO ON FIELD TRIPS",'scattergories','J4'),
("PICNIC THINGS",'scattergories','J5'),
("STUFF YOU WEAR ON THE WEEKEND",'scattergories','J5'),
("MOVIES",'scattergories','J5'),
("THINGS AT A BASEBALL GAME",'scattergories','J5'),
("THINGS AT AN AMUSEMENT PARK",'scattergories','J5'),
("THINGS AT THE MALL",'scattergories','J5'),
("STREET NAMES",'scattergories','J6'),
("THINGS IN A LIBRARY",'scattergories','J6'),
("THINGS IN A FIRE STATION",'scattergories','J6'),
("PEOPLE IN YOUR NEIGHBORHOOD",'scattergories','J6'),
("PLACES TO EAT",'scattergories','J6'),
("THINGS IN A POLICE STATION",'scattergories','J6'),
("OUTDOOR ACTIVITIES",'scattergories','J7'),
("AFTER SCHOOL SNACKS",'scattergories','J7'),
("TV SHOWS",'scattergories','J7'),
("TOYS OR GAMES",'scattergories','J7'),
("AFTER SCHOOL HANGOUTS",'scattergories','J7'),
("AFTER SCHOOL CHORES",'scattergories','J7'),
("THINGS YOU BRING",'scattergories','J8'),
("PLACES YOU'D LIKE TO GO",'scattergories','J8'),
("THINGS YOU TAKE PICTURES OF",'scattergories','J8'),
("SOMETHING AT THE BEACH",'scattergories','J8'),
("CAMP STUFF",'scattergories','J8'),
("SEEN FROM THE CAR WINDOW",'scattergories','J8'),
("SHORT WORDS",'scattergories','J9'),
("LONG WORDS",'scattergories','J9'),
("WORDS ABOUT MONEY",'scattergories','J9'),
("ACTION WORDS",'scattergories','J9'),
("WORDS ABOUT SPORTS",'scattergories','J9'),
("WORDS ABOUT MUSIC",'scattergories','J9'),
("A PERSON YOU LIKE",'scattergories','J10'),
("SOMETHING YOU HATE TO DO",'scattergories','J10'),
("SOMETHING YOU WISH FOR",'scattergories','J10'),
("SOMETHING YOU'RE GOOD AT",'scattergories','J10'),
("SOMETHING THAT'S GROSS",'scattergories','J10'),
("SOMETHING THAT MAKES YOU HAPPY",'scattergories','J10'),
("THINGS AT A PARADE",'scattergories','J11'),
("WAYS TO MAKE MONEY",'scattergories','J11'),
("SONGS OR SINGERS",'scattergories','J11'),
("WAYS TO BUG THE BABYSITTER",'scattergories','J11'),
("SOMETHING SCARY",'scattergories','J11'),
("SOMETHING IN YOUR BEDROOM",'scattergories','J11'),
("SOMEBODY COOL",'scattergories','J12'),
("THINGS AT A BIRTHDAY PARTY",'scattergories','J12'),
("THINGS THAT MAKE NOISE",'scattergories','J12'),
("FAST THINGS",'scattergories','J12'),
("THINGS AT A WEDDING",'scattergories','J12'),
("PLACES OR THINGS ON A MAP",'scattergories','J12');